function outputArg = probScores( s )
outputArg = struct( 'crps', nan( s ), ...
    'brier', struct( 'bs', nan( [s, 1] ), ...
             'rel', nan( [s, 1] ), ...
             'res', nan( [s, 1] ), ...
    'unc', nan( [s, 1] )) );